default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5
  
development:
  <<: *default
  database: messaging_board_development

test:
  <<: *default
  database: messaging_board_test
